Linker issues - thresholds done for LEDs
Everything done but cannot test it on the board due to memory issues,
getting lots of linker errors due to memory running out - will need to
consider taking out some code from the previous example code.

List of errors:
filter.o: Link Error: Could not allocate section .ndata, size = 376
bytes, attributes = data near main.o: Link Error: Could not allocate
section .nbss, size = 22 bytes, attributes = bss near sask.o: Link
Error: Could not allocate section .nbss, size = 4 bytes, attributes =
bss near OCPWMDrv.o: Link Error: Could not allocate section .nbss, size
= 2 bytes, attributes = bss near errno.o: Link Error: Could not
allocate section .nbss, size = 2 bytes, attributes = bss near  Link
Error: Could not allocate data memoryLink step failed.